### PR TITLE
Basic Login page, not working

### PR DESCRIPTION
**Pull request by eckertalex**
Please review the following items before creating your pull request.

-   [x] Descriptive pull request name

### CODE REVIEW

**Comment by Askaholic** [comment]
@eckertalex Is there a reason why this hasn't been merged yet?

**Comment by eckertalex** [comment]
@Askaholic because it does not work. @jjacobson wanted me to push it and create a pull request so that he can pull it and work on it.

**Comment by Askaholic** [comment]
@eckertalex huh. Creating s pull request without merging it doesn’t change the code though. You will still have to merge it so that he can pull. Or he can add your repo as a remote and pull from it directly in which case you don’t need this PR

**Comment by jjacobson** [comment]
Yes I realized I could just add his repo as a remote branch afterwards, so I did that instead. So we could probably close this unless you want to merge in the work that has been done so far.

**Comment by Askaholic** [comment]
Ah ok. I’ll merge it in just so everyone has the code.

**Pull request merged**
